<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('567', '/9010cms/uploads/ad/adnew.png');
$maNum = 1;
$myaddons[$maNum] = array('569', '/9010cms/uploads/ad/adnew.png');
$maNum = 2;
$myaddons[$maNum] = array('582', '/9010cms/uploads/ad/adnew.png');
$maNum = 3;
$myaddons[$maNum] = array('586', '/9010cms/uploads/ad/adnew.png');
$maNum = 4;
$myaddons[$maNum] = array('587', '/9010cms/uploads/ad/adnew.png');
$maNum = 5;
$myaddons[$maNum] = array('589', '/9010cms/uploads/ad/adnew.png');
$maNum = 6;
$myaddons[$maNum] = array('591', '/9010cms/uploads/ad/adnew.png');
$maNum = 7;
