<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5L+h5oGv57G7LeWFrOWPuOaWsOmXuw==');
$cfg_Cs[2]=array(0,2,1,'44CQ6aKE55WZ5o6l5Y+j44CR5Zu+54mH6ZuGLeS/g+mUgOa0u+WKqA==');
$cfg_Cs[3]=array(0,1,1,'44CQ6aKE55WZ5o6l5Y+j44CR5YW25LuW54mI5Z2X');
$cfg_Cs[4]=array(0,1,1,'44CQ6aKE55WZ5o6l5Y+j44CR5YW25LuW54mI5Z2X');
$cfg_Cs[5]=array(0,1,1,'5L+h5oGvLeaLm+iBmOS/oeaBrw==');
$cfg_Cs[6]=array(1,1,1,'572u6aG2');
$cfg_Cs[14]=array(0,1,1,'5L+h5oGv57G7LeaWsOWTgeWwnemynA==');
$cfg_Cs[8]=array(3,1,1,'572u6aG2');
$cfg_Cs[9]=array(4,1,1,'572u6aG2');
$cfg_Cs[10]=array(5,1,1,'572u6aG2');
$cfg_Cs[11]=array(0,2,1,'44CQ6aKE55WZ5o6l5Y+j44CR5Zu+54mH6ZuGLeaWsOWTgeWwnemynA==');
$cfg_Cs[12]=array(0,1,1,'6KeG6aKRLeWFrOWPuOi1hOiurw==');
$cfg_Cs[13]=array(0,1,1,'5L+h5oGv57G7LeS/g+mUgOa0u+WKqA==');
$cfg_Cs[15]=array(14,1,1,'572u6aG2');
?>