<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /9010cms/uploads/allimg/160802/1-160P2105U4.jpg ",93,279);
$z[1][4]['ddimg']="/9010cms/uploads/allimg/160802/1-160P2105U4.jpg";
$z[1][4]['text']="秋日风景图，美美哒";
$z[1][4]['width']="352";
$z[1][4]['height']="220";
$z[2]=Array("img"," /9010cms/uploads/allimg/160802/1-160P2105U4-50.jpg ",281,473);
$z[2][4]['ddimg']="/9010cms/uploads/allimg/160802/1-160P2105U4-50.jpg";
$z[2][4]['text']="夏日风景图，美美哒";
$z[2][4]['width']="330";
$z[2][4]['height']="220";
$z[3]=Array("img"," /9010cms/uploads/allimg/160802/1-160P2105U4-51.jpg ",475,667);
$z[3][4]['ddimg']="/9010cms/uploads/allimg/160802/1-160P2105U4-51.jpg";
$z[3][4]['text']="春日风景图，美美哒";
$z[3][4]['width']="329";
$z[3][4]['height']="220";
$z[4]=Array("img"," /9010cms/uploads/allimg/160802/1-160P2105U4-52.jpg ",669,861);
$z[4][4]['ddimg']="/9010cms/uploads/allimg/160802/1-160P2105U4-52.jpg";
$z[4][4]['text']="冬日风景图，美美哒";
$z[4][4]['width']="352";
$z[4][4]['height']="220";

?>