<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /9010cms/uploads/allimg/2016-08/02104033-1-1O57.jpg ",93,209);
$z[1][4]['ddimg']="";
$z[1][4]['text']="";
$z[1][4]['width']="352";
$z[1][4]['height']="220";
$z[2]=Array("img"," /9010cms/uploads/allimg/2016-08/02104033-1-2P28.jpg ",211,327);
$z[2][4]['ddimg']="";
$z[2][4]['text']="";
$z[2][4]['width']="330";
$z[2][4]['height']="220";
$z[3]=Array("img"," /9010cms/uploads/allimg/160802/1-160P2103927.jpg ",329,442);
$z[3][4]['ddimg']="";
$z[3][4]['text']="";
$z[3][4]['width']="329";
$z[3][4]['height']="220";

?>