{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154603.jpg' text='我们像是表面上的针，不停的转动，一面转，一面看着时间匆匆离去，却无能为力。' width='326' height='220'} /9010cms/uploads/allimg/160802/1-160P2154603.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154604.jpg' text='我们像是表面上的针，不停的转动，一面转，一面看着时间匆匆离去，却无能为力。' width='330' height='220'} /9010cms/uploads/allimg/160802/1-160P2154604.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154604-50.jpg' text='我们像是表面上的针，不停的转动，一面转，一面看着时间匆匆离去，却无能为力。' width='352' height='220'} /9010cms/uploads/allimg/160802/1-160P2154604-50.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154604-51.jpg' text='我们像是表面上的针，不停的转动，一面转，一面看着时间匆匆离去，却无能为力。' width='347' height='220'} /9010cms/uploads/allimg/160802/1-160P2154604-51.jpg {/dede:img}
