{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154I8.jpg' text='我忘了哪年哪月的哪一日我在哪面墙上刻下一张脸一张微笑着忧伤着凝望我的脸。' width='352' height='220'} /9010cms/uploads/allimg/160802/1-160P2154I8.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154I9.jpg' text='我忘了哪年哪月的哪一日我在哪面墙上刻下一张脸一张微笑着忧伤着凝望我的脸。' width='324' height='220'} /9010cms/uploads/allimg/160802/1-160P2154I9.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154I9-50.jpg' text='我忘了哪年哪月的哪一日我在哪面墙上刻下一张脸一张微笑着忧伤着凝望我的脸。' width='330' height='220'} /9010cms/uploads/allimg/160802/1-160P2154I9-50.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154I9-51.jpg' text='我忘了哪年哪月的哪一日我在哪面墙上刻下一张脸一张微笑着忧伤着凝望我的脸。' width='326' height='220'} /9010cms/uploads/allimg/160802/1-160P2154I9-51.jpg {/dede:img}
