{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154344.jpg' text='或许，最美的事不是留住时光，而是留住记忆，如最初相识的感觉一样，哪怕一个不经意的笑容，便是我们最怀念的故事。但愿，时光，如初见。' width='382' height='220'} /9010cms/uploads/allimg/160802/1-160P2154344.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154344-50.jpg' text='或许，最美的事不是留住时光，而是留住记忆，如最初相识的感觉一样，哪怕一个不经意的笑容，便是我们最怀念的故事。但愿，时光，如初见。' width='331' height='220'} /9010cms/uploads/allimg/160802/1-160P2154344-50.jpg {/dede:img}
{dede:img ddimg='/9010cms/uploads/allimg/160802/1-160P2154345.jpg' text='或许，最美的事不是留住时光，而是留住记忆，如最初相识的感觉一样，哪怕一个不经意的笑容，便是我们最怀念的故事。但愿，时光，如初见。' width='342' height='220'} /9010cms/uploads/allimg/160802/1-160P2154345.jpg {/dede:img}
