
  <m:item name='用户管理' link='weibo_manage/user.php' ischannel='1' addalt='创建栏目' rank='weibo_see,weibo_user' target='main' />
  <m:item name='问答管理' link='weibo_manage/weibo_manage.php' rank='weibo_see,weibo_manage' target='main' />
  <m:item name='提问审核' link='weibo_manage/weibo_manage.php?act=check_list' rank='weibo_see,weibo_check' target='main' />
  <m:item name='评论管理' link='weibo_manage/comment_manage.php' rank='weibo_see,weibo_comment' target='main' />
  <m:item name='微博删除' link='weibo_manage/weibo_manage.php?act=del_list' rank='weibo_see,weibo_manage' target='main' />
