<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /9010cms/uploads/allimg/161012/1-161012104Z5.jpg ",93,272);
$z[1][4]['ddimg']="/9010cms/uploads/allimg/161012/1-161012104Z5.jpg";
$z[1][4]['text']="美美哒的荔枝";
$z[1][4]['width']="352";
$z[1][4]['height']="220";
$z[2]=Array("img"," /9010cms/uploads/allimg/161012/1-161012104Z5-50.jpg ",274,459);
$z[2][4]['ddimg']="/9010cms/uploads/allimg/161012/1-161012104Z5-50.jpg";
$z[2][4]['text']="好好看的荔枝";
$z[2][4]['width']="330";
$z[2][4]['height']="220";
$z[3]=Array("img"," /9010cms/uploads/allimg/161012/1-161012104Z5-51.jpg ",461,643);
$z[3][4]['ddimg']="/9010cms/uploads/allimg/161012/1-161012104Z5-51.jpg";
$z[3][4]['text']="美味的荔枝";
$z[3][4]['width']="330";
$z[3][4]['height']="220";

?>