<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /9010cms/uploads/allimg/161012/1-161012105104.jpg ",93,223);
$z[1][4]['ddimg']="";
$z[1][4]['text']="大大的苹果";
$z[1][4]['width']="800";
$z[1][4]['height']="1067";
$z[2]=Array("img"," /9010cms/uploads/allimg/161012/1-161012105104-50.jpg ",225,358);
$z[2][4]['ddimg']="";
$z[2][4]['text']="美味的苹果";
$z[2][4]['width']="800";
$z[2][4]['height']="1067";
$z[3]=Array("img"," /9010cms/uploads/allimg/161012/1-161012105104-51.jpg ",360,499);
$z[3][4]['ddimg']="";
$z[3][4]['text']="超级无敌大苹果";
$z[3][4]['width']="800";
$z[3][4]['height']="1067";

?>