<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /9010cms/uploads/allimg/161013/1-161013235600.jpg ",93,277);
$z[1][4]['ddimg']="/9010cms/uploads/allimg/161013/1-161013235600.jpg";
$z[1][4]['text']="百威川味鸡丝面";
$z[1][4]['width']="800";
$z[1][4]['height']="533";
$z[2]=Array("img"," /9010cms/uploads/allimg/161013/1-161013235605.jpg ",279,457);
$z[2][4]['ddimg']="/9010cms/uploads/allimg/161013/1-161013235605.jpg";
$z[2][4]['text']="百威杂酱面";
$z[2][4]['width']="800";
$z[2][4]['height']="533";

?>