<?php
$z[0]=Array("global","",104,131);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",143,175);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",222,248);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",580,605);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",645,888);
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[5]=Array("global","",980,1005);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",1813,1943);
$z[6][4]['row']="10";
$z[6][4]['getall']="1";
$z[6][4]['sort']="month";

?>